sudo: required
dist: trusty

language: node_js

cache: yarn

matrix:
  include:
    - os: osx
      node_js: 10
    - os: linux
      node_js: 10
      deploy:
        skip_cleanup: true
        on:
          tags: true
        provider: npm
        email: layerssss@gmail.com
        api_key:
          secure: tEF3w7tp7BV/LRfi9BhQTObLJuZ0ISe6lnRZxTw3OzuP/eQGIwMhwzzasAjCM2Lj71yPi8WQkHICb0KPl1+XFea0yMagcDogdO+uDT2iOy/ijeO0VeOIeoe+yYbbAIIuazeaJUgOI0wEbsbGMo9z5VdoQLlW9+Z3rzQdk7WMueCU3Xr6iqcRUGJ77jzAlLjU7hWTpzfAfr/yZKkP15qEjUOC4GrwSFDDwOAxoZTr6pMz5HTTftfaDR/6pIkheu0zq6EiAFUtkcW+WiovQeHGwTaR+VZajGmScVP9g8J98EqqFDUlvLzNLenlrmBXHlo3JqznJwp9lSYSCAkwUzn49rmNWWa/Zze/zNbezbWfaCiC2qbF2xVmcB5eO7YAFVlGlMXRluX7Rojc7N2KE7ET0uKrG5ZDnHWVnyVDOwM/3bmLIssCVyxIeNb9VcHovXS9uPXaehpQEVeaN/3lvwGacu+tPCLJW1HZv1VrF9uu3gjT3sM7+Uwb0igmLT4d3Mw6imab3ySl0t53MFFl+siubTf/EidTxvoa7gc2VSquWngU79AE/qu8XH1FJ1KdRxRdNL+ako6XN0pz+VKPFVVx29Z1juaIXHuAWtLpPqLYZPxlgDN7Hw7mWJ0aYQsF9Y8If4FgWeE9FOIDdRO8xg3coxmvFASiKhw8Adgh3nhcTes=

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
  - yarn

before_script:
  - export

script:
  - npm run lint
  - npm run dist

env:
  global:
    # GH_TOKEN
    - secure: RRqAaTTXBNPg7V+q+WJD/KTqXwkMBf0wQgM2L/xSTZ0fy5AM943V1pm425cVYp/Bv1LOCGrBNxpLI/bvDPgUC/SLUJQ40A7ihPkzbh1jLHU593vk+kMzUTHb115y18zjDYrYlMAzYqp/vJWbKYGPgDS9jvVO2Ta+WeCyMKjWkpuFK6EPftiav7MvtooLOF/E0oknpMxC2Lo/1fYARwzeQ0pJa7dgNWCWC+IIoJrodqoa42Ca/lgl07JI+a02xMv/6fya1jEFSJgDFOPt5KQ+zcMCb4i0oLkRDtGA+Gv6Xt4BOXRhZGz+S1ZhkmaEaJL9MeicQa5w8V0mJ5wbPjSCcrykKoOD4G+aKBzv9mriNo5cQJm4gS549T/ZrppBOLr3Hfrpb4dKZqX5WNTjdD8toL4DCa8WJmnxJ1Wefge+9eVvfvysL+eQzqqLq+jsMvTWOT9Se/4gzetmF+XD0dcdGKOwteA5Z1wgV2/Nl2bwFpgIfxdjMCLmZ9P4rGPRedWAhPWxvYuyaPU1B7jDawMQAQD+4KNwGV463mAJUMV6iiODYe+6STprCbg/2nRKIP7WUpymKoarldKZ2xtRklv8X/HccTPOQVPMevpNG2Su9o5Me4FCJKEin9avBN+tLQqtRlPTkWgsj2KQULt/K6vUaguSO2olrh1mY4BvT8P/UwM=
