sudo: required
dist: trusty

language: node_js

cache: yarn

matrix:
  include:
    - os: osx
      node_js: 10
    - os: linux
      node_js: 10
      deploy:
        skip_cleanup: true
        on:
          tags: true
        provider: npm
        email: layerssss@gmail.com
        api_key:
          secure: tEF3w7tp7BV/LRfi9BhQTObLJuZ0ISe6lnRZxTw3OzuP/eQGIwMhwzzasAjCM2Lj71yPi8WQkHICb0KPl1+XFea0yMagcDogdO+uDT2iOy/ijeO0VeOIeoe+yYbbAIIuazeaJUgOI0wEbsbGMo9z5VdoQLlW9+Z3rzQdk7WMueCU3Xr6iqcRUGJ77jzAlLjU7hWTpzfAfr/yZKkP15qEjUOC4GrwSFDDwOAxoZTr6pMz5HTTftfaDR/6pIkheu0zq6EiAFUtkcW+WiovQeHGwTaR+VZajGmScVP9g8J98EqqFDUlvLzNLenlrmBXHlo3JqznJwp9lSYSCAkwUzn49rmNWWa/Zze/zNbezbWfaCiC2qbF2xVmcB5eO7YAFVlGlMXRluX7Rojc7N2KE7ET0uKrG5ZDnHWVnyVDOwM/3bmLIssCVyxIeNb9VcHovXS9uPXaehpQEVeaN/3lvwGacu+tPCLJW1HZv1VrF9uu3gjT3sM7+Uwb0igmLT4d3Mw6imab3ySl0t53MFFl+siubTf/EidTxvoa7gc2VSquWngU79AE/qu8XH1FJ1KdRxRdNL+ako6XN0pz+VKPFVVx29Z1juaIXHuAWtLpPqLYZPxlgDN7Hw7mWJ0aYQsF9Y8If4FgWeE9FOIDdRO8xg3coxmvFASiKhw8Adgh3nhcTes=

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
  - yarn

before_script:
  - export

script:
  - npm run lint
  - npm run dist

env:
  global:
    # GH_TOKEN
    - secure: HbISeWaa8/bSeJ8IQ4SxZHEfNHOMkVdE526fdKb03UejXzY6OWIoLc5BC6yTcQDepA+V/FQbtaQAAJx46/LHyGK4Dya5Vl/2qomrcubSbhk8EGHiQRoAkM59HOy7h30fiMzWdb0KMCZOYqf1Q6Yg3KZl51awBiPs1c/2nyZ+2BqHLCUxDzzoX32Kw3q0TNdt4RVDL6eMpoFEUx4YL0em51pA/tXDnxGcnPwg6qmY4ujmkStUBYh2OyGM9FQeJphGukF68RXbSD1MpEUxnXQYyQ9gIfGjM7xTS9WGAzxAePbjxZ3bRR5jIp1glFjdSzLVDgIZvd/7+ZRIH3pTz9DXjZicmBzS+VcQ6HZHUCgbvyqUDj0eBn5Lc2tkG+Oki1nzMfl3USKA58wXUnGpyvztDOsy8ZAVjwXWVdmSIbiJ8+JL7ZvO8eoAoLT240fNaP23jGr/yKjBOgRkaVjng2+DlNdVxQY4bBG8KJCVU58SicqCDEQpatTyoRpvXbPJWXbQjk41s2T7dscmfPzxQWh2bvcN3cUTLAgIxeUiQJN2FHNaTSx7759BSgXtcE7Ps04wlrVBMcpWNqkeWVwR0EZxqsupgA1xiv/J+upyO0vSZ01BJ5ksEbEgNr6BK22ybtTfCxeZdf5DkawlO3mkaXexN0LJneSHrkqWDqUUGYod4vk=
    # CSC_LINK
    - secure: "3zVbbMuKWIHXr/puJGdTaqsyVyMi6L4OeM5Y1/cSsox1dFmQmGQb8FXe/MCBOIXJLJP9G0uQrOU8Bq5XKvueTsGIrI8Wul9/jQKcQUDQVNxF6u0tH52t96IinxN1Pw+CiNn8dXbaGheceUHMuZy62lIrTmaAFqaxPxKNbr3Nbp7Y3SGCm2jeDAuOshqKpCAS9eidt9bQI57Unj7TfY7+0ZkCCsfUyPpBfbw4+5YV2VULBL511no2nWMM3GkCP0tLx0XQ87ckb3j3I2OWW+Z2ULXrt3igVuOsX1KGO0odcFf70d+KEFOfrLQE+aoaDQOsJ/JPY6Ju3+SCJZKqSWoa1mNTTTfFY67usFkK5APRBRBWruh+XaMWqFxmVXcel0RG9v66O6JrUkJbfI7Oo3x85nop7bJksY5K8hJHpy5NgKQiEfZK3YpAvwsqjpIM/osGT5J3bGlAXhZjpYTdrbnMx3ufqH7Tr6a3CXeeJe/e4nKicMwd/geLQqbCk3X2jBLiA7qzJXCtpiaJi3g1nPvo7pbNAwacK8gRygh1GSLh9ZJ7l9MCeo/NTSHXKLTwuRB1z0xmtT0r0NkiSjgD2vuV8D9ZNnnRAhKUNDMFyYFOweJwNex5kre6yVpkUzsMmcwMsHXQpUkhJ28o9L/aH73w81X63VFTazZeergYtosj600="
    # CSC_KEY_PASSWORD
    - secure: "UUdhjfrgoBzFlcckEVROix0DTd5MtIQ8y5TVx/+18jYt2yJnFzFblc7OUDigeeC/BqRynsSH4S05EJkA+jSRyZruiBfd/kWDvY8kC+uan3BKfWC8Q+XZwRb64+Tx065U8gXhFByhn2fk1EU83mu1OwnzWvoiY5j2uXb5OC7Mbp18QKdZEkvYDKwNkQrjSroSqrk8fhbAcWutFeJQVY/JoM81r4D1Rz2TU4ViexMlIIwOrd9rbH1pwjJMT5RE2P/GQTOv1oZY2x4gwIF62Kmqeg6pYGIS8b5piONduaOlfzWoKmXggMG8mtgE1CwmnRpg3PYpN4OODhMcGe1+7evpsm3pjDVRVns55zazDPbsgOhc0NM9L9IQy9tUsCj/uipzhgPbeJK5JcvorKKy5sXp/9np7wR3yvq3ETas4VvN33N539qTQoSKnPB+xN0OG9Vvk0avCchtdPo7qAQYFF6pjy53O4JeQKNZ7jctgfcAPrNvJAW9Dao4E8w66V5KVTJeyc05BB1a095QHdYgcQiYRS0bnZniAB80wgou6GnFjRU3aDB+nAyjF8Cp4krTruHs0p7Tt3MAzfCJ2JFm4d+5ViIy2NYxhQ03i/rixG3euI9iCBgnxNjFqj24QoGz/sbpoeJsgFy0r7jw2NOhO48NBa3+VnWtoEOm4xfThNvxoqg="
