sudo: required
dist: trusty

language: node_js

cache: yarn

matrix:
  include:
    - os: osx
      node_js: 10
    - os: linux
      node_js: 10
      deploy:
        skip_cleanup: true
        on:
          tags: true
        provider: npm
        email: layerssss@gmail.com
        api_key:
          secure: tEF3w7tp7BV/LRfi9BhQTObLJuZ0ISe6lnRZxTw3OzuP/eQGIwMhwzzasAjCM2Lj71yPi8WQkHICb0KPl1+XFea0yMagcDogdO+uDT2iOy/ijeO0VeOIeoe+yYbbAIIuazeaJUgOI0wEbsbGMo9z5VdoQLlW9+Z3rzQdk7WMueCU3Xr6iqcRUGJ77jzAlLjU7hWTpzfAfr/yZKkP15qEjUOC4GrwSFDDwOAxoZTr6pMz5HTTftfaDR/6pIkheu0zq6EiAFUtkcW+WiovQeHGwTaR+VZajGmScVP9g8J98EqqFDUlvLzNLenlrmBXHlo3JqznJwp9lSYSCAkwUzn49rmNWWa/Zze/zNbezbWfaCiC2qbF2xVmcB5eO7YAFVlGlMXRluX7Rojc7N2KE7ET0uKrG5ZDnHWVnyVDOwM/3bmLIssCVyxIeNb9VcHovXS9uPXaehpQEVeaN/3lvwGacu+tPCLJW1HZv1VrF9uu3gjT3sM7+Uwb0igmLT4d3Mw6imab3ySl0t53MFFl+siubTf/EidTxvoa7gc2VSquWngU79AE/qu8XH1FJ1KdRxRdNL+ako6XN0pz+VKPFVVx29Z1juaIXHuAWtLpPqLYZPxlgDN7Hw7mWJ0aYQsF9Y8If4FgWeE9FOIDdRO8xg3coxmvFASiKhw8Adgh3nhcTes=

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
  - yarn

before_script:
  - export

script:
  - npm run lint
  - npm run dist

env:
  global:
    # GH_TOKEN
    - secure: mUZtCLOFQh1Lbv53XegPYa6JrQtLyMZUbEsL/DBDxvpvfoFHUSFN4m6Dicm5AcXpan2tXpLI+jqz7YL0LTVHiqQXoWLM3GGmSxFIdfmPy+akWGa9l5IoUoZVyvW5ilu3QNzrM4uSItY6vnW/xhDoyI4UsHSMWzVg0Nl+jhLThwSl+XHrM/2tHb34Y7+Jfiuu1SZ7a/VaICh69E1EMh/3o5VDfkFr/rtY+oZz9QrqapPqkyZaaA1X/2IYTEZUOc4Ti0cEQ2+SASpuKYgxKweGklLtmNYKcWVMj2kSjacOrtZRIxSyRADqyJEIhq6ZL8PprFR/QI01OIl55bBMAFNOMsuQgft5O8MVtXsutV+Skt/N2jRpFGf4X9nUeh6mcFM0Sg4CHSPIqQthMg6aDhSooKUKeEXmhl9+vcr1Sq2sChPAx9r50JdZqtCVCao/HL9zimGbVU8Kx6+PtKOgzqh3gyEPbpaU2roAUrG9hd6q8vG2S6wDZP9VkFSAl9Hq0julTnH25MH/oZAFiLTYBFD/xkRhvHY2ysNJOJJ2ETKzmo8vBDSMe4V4AqXiXE3IM72/CL671Jywc3XhuYzZjCiCQoO7VXWQvfq4OZ7w4HoD+e9a9RCTMIQ6MEEooY0+LPhCGgNazgLgJ/WS6ulTrEODpb3oX69C3AdbkeQeET31Q2s=
