sudo: required
dist: trusty

language: node_js

cache: yarn

matrix:
  include:
    - os: osx
      node_js: 10
    - os: linux
      node_js: 10
      deploy:
        skip_cleanup: true
        on:
          tags: true
        provider: npm
        email: layerssss@gmail.com
        api_key:
          secure: tEF3w7tp7BV/LRfi9BhQTObLJuZ0ISe6lnRZxTw3OzuP/eQGIwMhwzzasAjCM2Lj71yPi8WQkHICb0KPl1+XFea0yMagcDogdO+uDT2iOy/ijeO0VeOIeoe+yYbbAIIuazeaJUgOI0wEbsbGMo9z5VdoQLlW9+Z3rzQdk7WMueCU3Xr6iqcRUGJ77jzAlLjU7hWTpzfAfr/yZKkP15qEjUOC4GrwSFDDwOAxoZTr6pMz5HTTftfaDR/6pIkheu0zq6EiAFUtkcW+WiovQeHGwTaR+VZajGmScVP9g8J98EqqFDUlvLzNLenlrmBXHlo3JqznJwp9lSYSCAkwUzn49rmNWWa/Zze/zNbezbWfaCiC2qbF2xVmcB5eO7YAFVlGlMXRluX7Rojc7N2KE7ET0uKrG5ZDnHWVnyVDOwM/3bmLIssCVyxIeNb9VcHovXS9uPXaehpQEVeaN/3lvwGacu+tPCLJW1HZv1VrF9uu3gjT3sM7+Uwb0igmLT4d3Mw6imab3ySl0t53MFFl+siubTf/EidTxvoa7gc2VSquWngU79AE/qu8XH1FJ1KdRxRdNL+ako6XN0pz+VKPFVVx29Z1juaIXHuAWtLpPqLYZPxlgDN7Hw7mWJ0aYQsF9Y8If4FgWeE9FOIDdRO8xg3coxmvFASiKhw8Adgh3nhcTes=

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
  - yarn

before_script:
  - export

script:
  - npm run lint
  - npm run dist

env:
  global:
    # GH_TOKEN
    - secure: 2g88sxrs/ZYpE4uaEt8DxJDF8KCtWznc+HN5tefHjsldhjwNliag+cfZI+QM0GBoDCII+wvVHko6YxdmKNNFpaWLb7QtsodT2VaKnKvDkap0oefWQAJf8Fgyj4y7tLQas8VODnS/c9HX5ZFxW2ZkJLY2uKhzjYk6ndOBoFbB7lOUxOE1/wFe4SCjGmlJBSuuI1rORA4xNiX+5f94ugDxPTGYL0WlI9tZmONkWcBpynnvvIQ05SzqDJPC+lEHTERowMe7aJxpR2bqZ0KlV+/fWL8p9m5YUfWMPxElSbp8Be9dUX3CZFw+jEXcI2sRQlVLLuGpfVfhwzd12O1dxKhuWNXSA+4GWvNmtuDMDiGTMhdQ4q5uCw39FqZ/34au5V1j/UPwD+CUqxpavy2pY3o8K2YBTE/0jRpiGzutUWwWbp6VnjmoiG403bk2GlSlB5BOniZZYvSC25FAvd6aWST1+VWggRIi7LuLfdbwo1NqZlWEZahUQxCOM68AEJyRSiwyLwQt24Ar3M1RalBAXCcWsnHwkfVBoWe1riYTkB9N5hMUeHCjN6zwHTgXr3I/N4TRjWyC/OBUL3p0BddnqsF1OLFr0GbRnbM6LrpZDMEpta/FaNpLzU/btI/YkFOKsqOco9bB75ZicVFBKfHSbNkG7pB3UWel/i4aUTYVkghiAnQ=
