# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64
  GH_TOKEN:
    secure: k9cHlRwf5Myhf4kCiwT55h+jM2gxHGrzlV4GRY/YucQMe49xzQztv14qrbbG/or2

image: Visual Studio 2017

init:
  - npm config set msvs_version 2017 # we need this to build `pty.js`

install:
  - ps: Install-Product node 10.16 x64
  - set CI=true
  - yarn

build_script:
  - yarn lint
  - yarn dist

shallow_clone: true

test_script:
  - node --version
  - yarn --version

on_success:
  - ps: Get-ChildItem .\dist\*\*.exe | % { Push-AppveyorArtifact $_.FullName }
