# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64
  GH_TOKEN:
    secure: 7moc7K09PVs71ThsO2x9DnFoaaJBofzs4yYfhXJdUZffbQeWdzO0zx8ZNp0zPL5p

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - npm run lint
  - npm run dist

shallow_clone: true

test_script:
  - node --version
  - npm --version

on_success:
  - ps: ls .\dist\win\*.exe | % { Push-AppveyorArtifact $_.FullName }
